apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nidhogg-rbac
subjects:
- kind: ServiceAccount
  name: nidhogg-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: nidhogg-admin
  apiGroup: rbac.authorization.k8s.io